/** @format */

import { QuestradeClass } from '../../core/types';

export async function allOfGetEquitySymbols(qt: QuestradeClass) {
  let equitySymbols = await qt.getEquitySymbols('aapl');
  equitySymbols = await qt.getEquitySymbols('8049');
  equitySymbols = await qt.getEquitySymbols(8049);
  const equitySymbol = equitySymbols[0];
  console.log(equitySymbol);
  console.log('equitySymbol.symbol:');
  console.log(equitySymbol.symbol);
  console.log('equitySymbol.symbolId:');
  console.log(equitySymbol.symbolId);
  console.log('equitySymbol.description:');
  console.log(equitySymbol.description);
  console.log('equitySymbol.securityType:');
  console.log(equitySymbol.securityType);
  console.log('equitySymbol.listingExchange:');
  console.log(equitySymbol.listingExchange);
  console.log('equitySymbol.isQuotable:');
  console.log(equitySymbol.isQuotable);
  console.log('equitySymbol.isTradable:');
  console.log(equitySymbol.isTradable);
  console.log('equitySymbol.currency:');
  console.log(equitySymbol.currency);
  console.log('equitySymbol.prevDayClosePrice:');
  console.log(equitySymbol.prevDayClosePrice);
  console.log('equitySymbol.highPrice52:');
  console.log(equitySymbol.highPrice52);
  console.log('equitySymbol.lowPrice52:');
  console.log(equitySymbol.lowPrice52);
  console.log('equitySymbol.averageVol3Months:');
  console.log(equitySymbol.averageVol3Months);
  console.log('equitySymbol.averageVol20Days:');
  console.log(equitySymbol.averageVol20Days);
  console.log('equitySymbol.outstandingShares:');
  console.log(equitySymbol.outstandingShares);
  console.log('equitySymbol.eps:');
  console.log(equitySymbol.eps);
  console.log('equitySymbol.pe:');
  console.log(equitySymbol.pe);
  console.log('equitySymbol.dividend:');
  console.log(equitySymbol.dividend);
  console.log('equitySymbol.yield:');
  console.log(equitySymbol.yield);
  console.log('equitySymbol.exDate:');
  console.log(equitySymbol.exDate);
  console.log('equitySymbol.marketCap:');
  console.log(equitySymbol.marketCap);
  console.log('equitySymbol.tradeUnit:');
  console.log(equitySymbol.tradeUnit);
  console.log('equitySymbol.optionType:');
  console.log(equitySymbol.optionType);
  console.log('equitySymbol.optionDurationType:');
  console.log(equitySymbol.optionDurationType);
  console.log('equitySymbol.optionRoot:');
  console.log(equitySymbol.optionRoot);
  console.log('equitySymbol.optionContractDeliverables:');
  console.log(equitySymbol.optionContractDeliverables);
  console.log('equitySymbol.optionExerciseType:');
  console.log(equitySymbol.optionExerciseType);
  console.log('equitySymbol.optionExpiryDate:');
  console.log(equitySymbol.optionExpiryDate);
  console.log('equitySymbol.dividendDate:');
  console.log(equitySymbol.dividendDate);
  console.log('equitySymbol.optionStrikePrice:');
  console.log(equitySymbol.optionStrikePrice);
  console.log('equitySymbol.hasOptions:');
  console.log(equitySymbol.hasOptions);
  console.log('equitySymbol.minTicks:');
  console.log(equitySymbol.minTicks);
  console.log('equitySymbol.industrySector:');
  console.log(equitySymbol.industrySector);
  console.log('equitySymbol.industryGroup:');
  console.log(equitySymbol.industryGroup);
  console.log('equitySymbol.industrySubgroup:');
  console.log(equitySymbol.industrySubgroup);
}
