/** @format */

import { QuestradeClass } from '../../core/types';

export async function allOfgetServerTimeObject(qt: QuestradeClass, done: any) {
  const getServerTimeObject = await qt.getServerTimeObject();
  const getServerTime = await qt.getServerTime;
  await console.log('\n\n\n\nGETSERVERTIME:');
  await console.log('\n\ngetServerTime:');
  await console.log(getServerTime);
  await console.log('serverTime:');
  await console.dir(getServerTimeObject.serverTime);
  await console.log('UTC:');
  await console.dir(getServerTimeObject.UTC);
  await console.log('timeObject.years:');
  await console.dir(getServerTimeObject.timeObject.years);
  await console.log('timeObject.months:');
  await console.dir(getServerTimeObject.timeObject.months);
  await console.log('timeObject.date:');
  await console.dir(getServerTimeObject.timeObject.date);
  await console.log('timeObject.hours:');
  await console.dir(getServerTimeObject.timeObject.hours);
  await console.log('timeObject.minutes:');
  await console.dir(getServerTimeObject.timeObject.minutes);
  await console.log('timeObject.seconds:');
  await console.dir(getServerTimeObject.timeObject.seconds);
  await console.log('timeObject.milliseconds:');
  await console.dir(getServerTimeObject.timeObject.milliseconds);
  await console.log('toUTCDate:');
  await console.dir(getServerTimeObject.toUTCDate);
  await console.log('toArray:');
  await console.dir(getServerTimeObject.toArray);
  await console.log('date.day:');
  await console.dir(getServerTimeObject.date.day);
  await console.log('date.date:');
  await console.dir(getServerTimeObject.date.date);
  await console.log('date.month:');
  await console.dir(getServerTimeObject.date.month);
  await console.log('date.year:');
  await console.dir(getServerTimeObject.date.year);
  await console.log('time.hour:');
  await console.dir(getServerTimeObject.time.hour);
  await console.log('time.minute:');
  await console.dir(getServerTimeObject.time.minute);
  await console.log('time.second:');
  await console.dir(getServerTimeObject.time.second);
  await console.log('time.milliseconds:');
  await console.dir(getServerTimeObject.time.milliseconds);
  await console.log('time.unixmilliseconds:');
  await console.dir(getServerTimeObject.time.unixmilliseconds);
  await console.log('time.unix:');
  await console.dir(getServerTimeObject.time.unix);
  await console.log('time.utcOffset:');
  await console.dir(getServerTimeObject.time.utcOffset);
  await console.log('isValid:');
  await console.dir(getServerTimeObject.isValid);
  await console.log('dayOfYear:');
  await console.dir(getServerTimeObject.dayOfYear);
  await console.log('weekOfTheYeay:');
  await console.dir(getServerTimeObject.weekOfTheYeay);
  await console.log('weekday:');
  await console.dir(getServerTimeObject.weekday);
  await console.log('isLeapYear:');
  await console.dir(getServerTimeObject.isLeapYear);
  await console.log('daysInMonth:');
  await console.dir(getServerTimeObject.daysInMonth);
  await console.log('weeksInYear:');
  await console.dir(getServerTimeObject.weeksInYear);
  await console.log('quarter:');
  await console.dir(getServerTimeObject.quarter);
  await console.log('locale:');
  await console.dir(getServerTimeObject.locale);
  done();
}
